;; Auto-mode
(setq auto-mode-alist
      '(("\\.c$" .             c-mode)
        ("\\.cc$" .            c++-mode)
        ("\\.cpp$" .           c++-mode)
        ("\\.cxx$" .           c++-mode)
        ("\\.cpp$" .           c++-mode)
        ("\\.ipp$" .           c++-mode)
        ("\\.i$" .             c++-mode)
        ("\\.ixx$" .           c++-mode)        
        ("\\.h$" .             c++-mode)
        ("\\.hh$" .            c++-mode)
        ("\\.hpp$" .           c++-mode)
        ("\\.hxx$" .           c++-mode)
        ("\\.el$" .            emacs-lisp-mode)
        ("\\.emacs$" .         emacs-lisp-mode)
        ("\\.sh$" .            shell-script-mode)
        ("^\\.bash.*" .        shell-script-mode)
        ("\\.pl$" .            perl-mode)
        ("\\.py$" .            python-mode)
        ("\\.awk$" .           awk-mode)
        ("Makefile\\(.*\\)$" . makefile-mode)
        ("\\.m$" .             octave-mode)
        ("\\.org$" .           org-mode)
        ("\\.scala$" .         scala-mode)
        ("\\.js$" .            js2-mode)
        ("\\.coffe$" .          js2-mode)
        ("\\.jade$" .          jade-mode)
        ("\\.java$" .          java-mode)
        ("\\.pde$" .           java-mode)
        ("\\.css$" .           all-css-modes)
        ("\\.html$" .          html-mode)))


(provide 'setup-auto-mode)
